[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# We embed remappings here so the compiler doesn't need a separate file
remappings = [
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/'
]

[profile.ci]
verbosity = 4